Aviva_FizzBuzz_Tapas_TDD/Aviva_FizzBuzz_Tapas_TDD/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aviva_FizzBuzz_Tapas_TDD.ViewModel;
using Aviva_FizzBuzz_Tapas_TDD.BL;

namespace Aviva_FizzBuzz_Tapas_TDD.Controllers
{
    public class FizzBuzzController : Controller
    {
        public IFizzBuzzViewModel FizzBuzzModel { get; set; }
       
        public FizzBuzzController(IFizzBuzzViewModel fizzBuzzModel)
        {
            FizzBuzzModel = fizzBuzzModel;
        }

        public ActionResult Show()
        {
            return View("Show");
        }
        public ActionResult Submit(string maxNumber)
        {
            if (ModelState.IsValid)
            {
                FizzBuzzModel.MaxNumber = Int32.Parse(maxNumber);
                FizzBuzzModel.GetFizzBuzzNumbers();
                return View("Show", FizzBuzzModel);
            }
            else
            {
                return View("Show", FizzBuzzModel);
            }
        }
    }
}

Aviva_FizzBuzz_Tapas_TDD/Aviva_FizzBuzz_Tapas_TDD/Views/FizzBuzz/Display.cshtml
@model Aviva_FizzBuzz_Tapas_TDD.ViewModel.FizzBuzzViewModel

<table>
    <tr><td><b><u>FizzBuzz Numbers</u></b></td></tr>
    @foreach (string fizzBuzzNumber in @Model.FizzBuzzNumbers)
    {
        <tr>
            <td><span>@fizzBuzzNumber</span> </td>
        </tr>
    }
</table>

Aviva_FizzBuzz_Tapas_TDD/Aviva_FizzBuzz_Tapas_TDD/Views/FizzBuzz/Show.cshtml
@model Aviva_FizzBuzz_Tapas_TDD.ViewModel.FizzBuzzViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show</title>
</head>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<body>
    <div> 
        @using (Html.BeginForm("Submit", "FizzBuzz", FormMethod.Post))
        {
            <i>Enter Maximum Number:</i>@Html.TextBoxFor(m => m.MaxNumber)
            <input id="Submit1" type="submit" value="Click Here" /><br />
            @Html.ValidationMessageFor(x => x.MaxNumber)
            <br />

            if (Model != null)
            {
                @Html.Partial("Display", Model)
            }
        }
    </div>
</body>
</html>